### ISSUE TITLE
uptimed: no useable database found.

### ISSUE THREAD

**Issue by amaurypm** [rpodgorny/uptimed#13]
Hello,
uprecords reports:

uptimed: no useable database found.

and then only shows the last uptime info, with no records of previous sessions (which is the idea of uptimed after all).

I am using uptimed 0.4.0, in Manjaro 17.0.5.
I have the same issue with Fedora 26.

Regards,

**Comment by luisc99** [comment]
Can confirm this also occurs on macOS Sierra 10.12.6, also with uptimed 0.4.0

**Comment by jimmyjules** [comment]
hi skotsjedal. I think this could be the solution. can you try to explain further what you've done? I don't get it.

**Comment by skotsjedal** [comment]
After installing, i ran `$ uptimed` manually to see, not knowing the uprecords command yet. This started uptimed a second time running as my own user.

    $ ps aux | grep uptimed
    daemon  4564  0.0  0.0    6428   652 ?         Ss    10:02   0:00 /usr/sbin/uptimed -f
    vagrant   4641  0.0  0.0    6428   104 ?         Ss    10:02   0:00 uptimed
    vagrant   4657  0.0  0.0  15756   980 pts/9    S+   10:02   0:00 grep --color=auto uptimed
    $ kill 4641

So I killed that one which seems to have fixed it
                                                    `

**Comment by hsmatis** [comment]
Thank you.  I had the exact same problem on a Raspberry Pi.  Kill the process solved my problem too.

**Comment by rpodgorny** [comment]
so this looks like a case of wrong usage. closing. thanks for helping one another! ;-)

**Comment by sid-the-sloth** [comment]
restart the service -- and all is fine:

`# systemctl restart uptimed`
