### ISSUE TITLE
duplicate entries, wrong downtime and uptime percentage

### ISSUE THREAD

**Issue by mar04** [rpodgorny/uptimed#2]
```
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
     1    22 days, 14:50:48 | Linux 3.15.7-1-ARCH       Sun Aug 10 21:26:49 2014
->   2    18 days, 17:13:35 | Linux 3.14.25-1-lts       Sat Nov 22 22:38:34 2014
     3    18 days, 17:12:46 | Linux 3.14.25-1-lts       Sat Nov 22 22:38:33 2014
     4    18 days, 00:11:22 | Linux 3.14.25-1-lts       Sat Nov 22 22:38:30 2014
     5    16 days, 18:24:54 | Linux 3.13.6-1-ARCH       Tue Mar 11 20:54:36 2014
     6    12 days, 16:10:36 | Linux 3.15.5-1-ARCH       Fri Jul 11 16:22:23 2014
     7    11 days, 18:48:03 | Linux 3.15.1-1-ARCH       Wed Jun 18 18:34:46 2014
     8    10 days, 05:24:05 | Linux 3.14.23-1-lts       Sun Nov  9 10:09:36 2014
     9     9 days, 09:05:34 | Linux 3.16.2-1-ARCH       Tue Sep  9 13:14:09 2014
    10     9 days, 06:44:06 | Linux 3.14.1-1-ARCH       Wed Apr 23 05:53:32 2014
----------------------------+---------------------------------------------------
no1 in     3 days, 21:37:14 | at                        Mon Dec 15 13:29:22 2014
    up   302 days, 16:47:08 | since                     Tue Mar 11 20:54:36 2014
  down  -27 days, -21:-49:- | since                     Tue Mar 11 20:54:36 2014
   %up              110.157 | since                     Tue Mar 11 20:54:36 2014
```

So the story is: When I run uprecords yesterday, I've noticed two entries for the same boot with marginally different dates. So I restarted uptimed with systemctl restart uptimed.service. To my surprise the duplicate entry was still there, but no longer updating. Some time later I've run uprecords again and another duplicate appeared. So entries 2,3,4, as seen above, are from the same boot.
I suspect this is connected to switching from chrony to systemd-timesyncd for ntp client on my system, because I've never seen this before. Uptimed version is 0.3.18.

**Comment by minshallj** [comment]
+1, I've had the same problem on ubuntu 14.10, which I think is still upstart, though it could be systemd...

The same thing happened for me when I restarted the daemon, `sudo service uptimed restart`, the duplicate stopped updating

```
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
     1    10 days, 11:22:27 | Linux 3.13.0-43-generic   Wed Dec 31 00:03:30 2014
->   2     5 days, 03:23:34 | Linux 3.13.0-43-generic   Sat Jan 10 11:26:01 2015
     3     5 days, 03:22:27 | Linux 3.13.0-43-generic   Sat Jan 10 11:26:05 2015
----------------------------+---------------------------------------------------
no1 in     5 days, 07:58:54 | at                        Tue Jan 20 22:48:27 2015
    up    20 days, 18:08:28 | since                     Wed Dec 31 00:03:30 2014
  down   -5 days, -03:-23:- | since                     Wed Dec 31 00:03:30 2014
   %up              132.926 | since                     Wed Dec 31 00:03:30 2014

```

**Comment by vitich** [comment]
Dirty "hack" :)
# cat /root/bin/uptimed-fix 
#!/bin/bash
while true 
do
if test -f "/var/spool/uptimed/records"; then
> /var/spool/uptimed/records
> /var/spool/uptimed/records.old
fi

# uprecords 
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
->   1     5 days, 23:44:48 | Linux 3.2.0-4-amd64       Thu Apr 23 11:01:15 2015
----------------------------+---------------------------------------------------
NewRec     5 days, 23:44:47 | since                     Thu Apr 23 11:01:15 2015
    up     5 days, 23:44:48 | since                     Thu Apr 23 11:01:15 2015
  down     0 days, 00:00:00 | since                     Thu Apr 23 11:01:15 2015
   %up              100.000 | since                     Thu Apr 23 11:01:15 2015

And it displays correctly now :)
I'll wait for fix. 
Thanks.

**Comment by vlumi** [comment]
I had this same issue, but can't recall how it occurred... Running version 0.3.17-3.1 on debian.
```
->  10    60 days, 20:56:40 | Linux 4.0.4-x86_64-linod  Sat May 30 09:21:49 2015
    11    60 days, 20:46:54 | Linux 4.0.4-x86_64-linod  Sat May 30 09:21:50 2015
```

Also royally messing the down and %up calculations:
```
  down   -60 days, -05:-12: | since                     Fri Sep 10 14:08:06 2010
   %up              103.376 | since                     Fri Sep 10 14:08:06 2010
```

Duplicate rows on both records and records.old files:
```
5259230:1432966909:Linux 4.0.4-x86_64-linode57
5258814:1432966910:Linux 4.0.4-x86_64-linode57
```

I could recover by stopping uptimed, deleting the lower row from both files, and then starting uptimed again.

**Comment by alminde** [comment]
This is happening for me too on OS X (`uptimed 0.4.0`) and Linux (`uptimed 0.3.17`). :sob:

**Comment by HaibaneNero** [comment]
Also having this issue on Ubuntu 15.04 (```uptimed 0.3.17```)

**Comment by ouafnico** [comment]
same problem on archlinux arm, and Centos 7 x86_64.
On arm, uptimed must start after ntp (modify the systemcl service).

$ uprecords 
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
->   1    37 days, 19:56:39 | Linux 4.3.0-2-ARCH        Sat Feb 13 23:34:37 2016
     2    32 days, 23:59:17 | Linux 4.3.0-2-ARCH        Mon Jan 11 11:50:12 2016
     3     0 days, 01:00:08 | Linux 4.3.0-2-ARCH        Sat Feb 13 22:31:53 2016
     4     0 days, 00:00:09 | Linux 4.3.0-2-ARCH        Thu Jan  1 01:00:17 1970
     5     0 days, 00:00:08 | Linux 4.3.0-2-ARCH        Thu Jan  1 01:19:26 1970
     6     0 days, 00:00:08 | Linux 4.3.0-2-ARCH        Thu Jan  1 01:10:03 1970
----------------------------+---------------------------------------------------
NewRec     4 days, 19:57:21 | since                     Thu Mar 17 23:33:55 2016
    up    70 days, 20:56:29 | since                     Thu Jan  1 01:00:17 1970
  down  16811 days, 21:34:3 | since                     Thu Jan  1 01:00:17 1970
   %up                0.420 | since                     Thu Jan  1 01:00:17 1970

==> 1970 :D :D 

But on CentOS after a reboot it's totally wrong don't know why. Seems some uptime info was not recorded before the reboot.

     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
     1    27 days, 18:21:04 | Linux 3.10.0-327.3.1.el7  Sat Dec 26 16:39:00 2015
     2    25 days, 19:26:17 | Linux 3.10.0-327.4.5.el7  Sun Feb 14 16:09:12 2016
->   3    11 days, 07:54:23 | Linux 3.10.0-327.10.1.el  Fri Mar 11 11:37:23 2016
----------------------------+---------------------------------------------------
1up in    14 days, 11:31:55 | at                        Wed Apr  6 08:03:41 2016
no1 in    16 days, 10:26:42 | at                        Fri Apr  8 06:58:28 2016
    up    64 days, 21:41:44 | since                     Sat Dec 26 16:39:00 2015
  down    22 days, 05:11:02 | since                     Sat Dec 26 16:39:00 2015
   %up               74.500 | since                     Sat Dec 26 16:39:00 2015


Any fix ?

**Comment by ljakab** [comment]
Piling on with an occurrence on macOS 10.14.4 using uptimed 0.4.1 from homebrew:

`~> /usr/local/opt/uptimed/bin/uprecords
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
->   1     5 days, 18:42:27 | Darwin 18.5.0             Tue Apr 30 20:53:01 2019
     2     5 days, 18:41:29 | Darwin 18.5.0             Tue Apr 30 20:52:59 2019
     3     1 day , 10:51:27 | Darwin 18.5.0             Mon Apr 29 09:58:54 2019
----------------------------+---------------------------------------------------
NewRec     0 days, 00:00:57 | since                     Mon May  6 15:34:30 2019
    up    13 days, 00:15:23 | since                     Mon Apr 29 09:58:54 2019
  down  -5 days, -18:-38:-4 | since                     Mon Apr 29 09:58:54 2019
   %up              179.861 | since                     Mon Apr 29 09:58:54 2019`

**Comment by perlun** [comment]
Seeing similar problems on my Debian GNU/Linux workstation:

```
$ uprecords 
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
->   1   118 days, 04:31:15 | Linux 4.19.0-1-amd64      Fri Jan 18 11:16:22 2019
     2   118 days, 03:49:56 | Linux 4.19.0-1-amd64      Fri Jan 18 11:16:25 2019
     3    69 days, 20:09:17 | Linux 4.18.0-2-amd64      Fri Nov  9 14:58:04 2018
     4    53 days, 19:48:49 | Linux 4.18.0-2-amd64      Fri Nov  9 14:58:05 2018
     5    47 days, 23:56:05 | Linux 4.18.0-2-amd64      Fri Nov  9 14:58:06 2018
     6    26 days, 19:52:33 | Linux 4.18.0-1-amd64      Wed Sep 19 11:56:45 2018
     7    17 days, 21:07:23 | Linux 4.17.0-3-amd64      Mon Aug 27 11:53:31 2018
     8    15 days, 03:29:40 | Linux 4.18.0-2-amd64      Tue Oct 16 08:30:17 2018
     9    15 days, 02:07:04 | Linux 4.18.0-2-amd64      Tue Oct 16 08:30:16 2018
    10     9 days, 02:48:33 | Linux 4.18.0-2-amd64      Wed Oct 31 11:09:06 2018
----------------------------+---------------------------------------------------
NewRec     0 days, 00:41:18 | since                     Thu May 16 16:06:19 2019
    up   503 days, 22:41:31 | since                     Mon Aug 20 16:04:27 2018
  down  -234 days, -22:-39: | since                     Mon Aug 20 16:04:27 2018
   %up              187.339 | since                     Mon Aug 20 16:04:27 2018
```

Just like for @minshallj, this was the same for me:

> The same thing happened for me when I restarted the daemon, sudo service uptimed restart, the duplicate stopped updating

**Comment by perlun** [comment]
Removing systemd-timesyncd to see if it helps, maybe it will:

```shell
$ sudo systemctl stop systemd-timesyncd
$ sudo systemctl disable systemd-timesyncd
Removed /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service.
$ sudo timedatectl set-ntp false
```

Also wiped the existing `/var/spool/uptimed/records` database; it's a shame to see it go but... :cry: What do you do.

**Comment by epsimatic** [comment]
I had the same issue once. Mac OS, installed via `homebrew`:

```
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
     1    38 days, 12:01:30 | Darwin 17.7.0             Mon Aug  6 12:08:28 2018
     2    38 days, 06:40:16 | Darwin 17.7.0             Mon Aug  6 11:16:06 2018
     3    33 days, 09:04:27 | Darwin 18.0.0             Fri Oct  5 09:56:03 2018
     4    30 days, 00:45:22 | Darwin 17.5.0             Fri May  4 13:20:00 2018
...
```

**Comment by jason-vivid** [comment]
+1 on Ubuntu 18.04.  See entries 4-7 below.

```
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
     1   110 days, 17:21:45 | Linux 5.1.11-x86_64-lino  Mon Jul  1 23:19:16 2019
     2    89 days, 06:24:45 | Linux 4.15.0-20-generic   Wed Apr  3 16:42:29 2019
     3    78 days, 00:55:37 | Linux 5.1.17-x86_64-lino  Sun Oct 20 17:03:58 2019
     4    63 days, 05:48:37 | Linux 5.3.11-x86_64-lino  Mon Jan  6 17:00:18 2020
     5     2 days, 21:59:33 | Linux 5.3.11-x86_64-lino  Mon Jan  6 17:00:17 2020
->   6     0 days, 08:49:08 | Linux 5.4.10-x86_64-lino  Mon Mar  9 23:50:41 2020
     7     0 days, 08:00:04 | Linux 5.4.10-x86_64-lino  Mon Mar  9 23:50:40 2020
----------------------------+---------------------------------------------------
1up in     2 days, 13:10:26 | at                        Thu Mar 12 21:50:14 2020
no1 in   110 days, 08:32:38 | at                        Sun Jun 28 17:12:26 2020
    up   344 days, 21:19:29 | since                     Wed Apr  3 16:42:29 2019
  down  -3 days, -05:-22:-0 | since                     Wed Apr  3 16:42:29 2019
   %up              100.944 | since                     Wed Apr  3 16:42:29 2019
```

**Comment by rpodgorny** [comment]
should be fixed by https://github.com/rpodgorny/uptimed/pull/22 (and later commits). if this is still an issue, please open a new issue. thanks!

**Comment by xtaran** [comment]
While testing a script which eliminates existing duplicate entries from the existing uptimed database based on @maciejsszmigiero's algorithm, on one Xen DomU (i.e. a VM) I stumbled upon this weird triple of entries (entries number 3, 4, and 5) which IMHO are clearly a there same boot, but seems to have about 2x 50 minutes offset (actually 1x 50min and 1x 50min and 1sec)  between the two boot dates while having recorded three times over 400 days of uptime:

```
$ uprecords -bm0
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
     1    64 days, 21:27:45 | Linux 3.3.0-trunk-amd64   Tue Apr  3 22:55:14 2012
     2     6 days, 16:54:31 | Linux 3.4-trunk-amd64     Thu Jun  7 20:33:20 2012
     3   675 days, 14:12:11 | Linux 3.4-trunk-amd64     Thu Jun 14 12:09:38 2012
     4   542 days, 06:27:28 | Linux 3.4-trunk-amd64     Thu Jun 14 12:59:38 2012
     5   460 days, 09:50:03 | Linux 3.4-trunk-amd64     Thu Jun 14 13:49:39 2012
[…]
```

Does anyone have an explanation for these 50 minutes offsets? Those are way off from @maciejsszmigiero's 30 second tolerance… Could suspending a VM to disk during a reboot of its host have caused this?

**Comment by xtaran** [comment]
@epsimatic wrote in 2019:
> I had the same issue once. Mac OS, installed via `homebrew`:
> 
> ```
>      #               Uptime | System                                     Boot up
> ----------------------------+---------------------------------------------------
>      1    38 days, 12:01:30 | Darwin 17.7.0             Mon Aug  6 12:08:28 2018
>      2    38 days, 06:40:16 | Darwin 17.7.0             Mon Aug  6 11:16:06 2018
> ```

JFTR: This is also more a 50 minutes than a 30 seconds offset. Actually it's a -47m48s offset, if I did the maths in mind correctly.

But that's also the only other example in this bug report which has more than those 30 seconds of offset. (Not counting those epoch-zero i.e. 1970-01-01 issues. These are other problems common on devices without RTC, especially Raspberry Pis.)

**Comment by epsimatic** [comment]
Had the same issue another time. `uprecords 0.4.6` installed via homebrew.

```
❯ uprecords
     #               Uptime | System                                     Boot up
----------------------------+---------------------------------------------------
->   1    74 days, 01:46:03 | Darwin 21.3.0             Fri Mar 11 14:02:44 2022
     2    74 days, 01:44:31 | Darwin 21.3.0             Fri Mar 11 14:03:40 2022
----------------------------+---------------------------------------------------
```

```
❯ grep . /usr/local/var/uptimed/records*
/usr/local/var/uptimed/records:6399918:1646996564:Darwin 21.3.0
/usr/local/var/uptimed/records:6399871:1646996620:Darwin 21.3.0
/usr/local/var/uptimed/records.old:6399904:1646996564:Darwin 21.3.0
/usr/local/var/uptimed/records.old:6399871:1646996620:Darwin 21.3.0
```

Fixed by:

- `brew services stop uptimed`
- **Make a backup, then** edit both files `/usr/local/var/uptimed/records*`,
  - remove duplicate lines from `records`
  - delete everything from `records.old`
- `brew services start uptimed`

**Comment by rpodgorny** [comment]
> So probably the problem still exists. Should I create a new issue for it?

yes, please (and link to it from here, please). also, please be advised that i don't have macos (and more importantly - i don't have time) to properly debug and fix this so i'll be reliant on user-provided patches... :-(

**Comment by daniel-mller-87** [comment]
Also exists for me on Debian. It's good to know the little hack
