### ISSUE TITLE
error: conditional "HAVE_SYSTEMD" was never defined

### ISSUE THREAD

**Issue by bfontaine** [rpodgorny/uptimed#4]
Hello, I’m trying to build `uptimed` on OS X, and this is what `./configure` give me:

```
(…)
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/sh: /Users/baptiste/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of clang... none
checking for getopt... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for getdtablesize... yes
checking that generated files are newer than configure... done
configure: error: conditional "HAVE_SYSTEMD" was never defined.
Usually this means the macro was only invoked conditionally.
```

I don’t know how to write automake/autoconf directives, but looking at the code `HAVE_SYSTEMD` is used in [`etc/Makefile.am`](https://github.com/rpodgorny/uptimed/blob/master/etc/Makefile.am#L5) but is only defined in the [`configure.ac`](https://github.com/rpodgorny/uptimed/blob/master/configure.ac#L20) script if one is using Linux. I removed the `if HAVE_SYSTEMD` condition in `Makefile.am` but it didn’t fix the issue.

**Comment by asparagui** [comment]
sugoi

**Comment by rpodgorny** [comment]
can you, please, try this branch?

https://github.com/rpodgorny/uptimed/tree/autotools-cleanup

it gets rid of the autotools generated stuff so you need to run autogen.sh (and then continue as usual).

**Comment by bfontaine** [comment]
Just tried, I get the same error. [Here is the log](https://gist.github.com/bfontaine/4199bcb3e505d6d869c8#file-log-L104-L105), I can provide you any more info you need.

**Comment by rpodgorny** [comment]
can you, please, try with the conditional moved out of the case as shown here?

https://github.com/hughsie/PackageKit/issues/17

**Comment by rpodgorny** [comment]
hmmm, anyway, i just noticed that as your system is defined as darwin, the systemd stuff should not apply... ...weird.

**Comment by bfontaine** [comment]
The following patch fixes the issue:

```diff
diff --git a/configure.ac b/configure.ac
index 9f0b9a2..e9e29b6 100644
--- a/configure.ac
+++ b/configure.ac
@@ -17,7 +17,6 @@ case "$host" in
             AC_SUBST([systemdsystemunitdir], [$with_systemdsystemunitdir])
             AC_OUTPUT([etc/uptimed.service])
         fi
-        AM_CONDITIONAL(HAVE_SYSTEMD, [test -n "$with_systemdsystemunitdir" -a "x$with_systemdsystemunitdir" != xno ])
     ;;
   *-hpux*)
     AC_DEFINE(PLATFORM_HPUX, 1, [Define if you are compiling for HP/UX])
@@ -54,6 +53,8 @@ case "$host" in
     ;;
 esac

+AM_CONDITIONAL(HAVE_SYSTEMD, [test -n "$with_systemdsystemunitdir" -a "x$with_systemdsystemunitdir" != xno ])
+
 AC_REPLACE_FUNCS(getopt)
 AC_CHECK_HEADERS(getopt.h)
 AC_CHECK_FUNCS([getdtablesize])
```

From what I understand, `HAVE_SYSTEMD` is used in the `Makefile.am` but is only defined in `configure.ac` if one is using Linux. Moving the definition at the bottom always define it, but it’s always false for people who don’t use Linux.

**Comment by rpodgorny** [comment]
thank you very much for your cooperation. the fix is now committed and i'll make a new release, soon (with the cleaned-up autotools branch included).

**Comment by bfontaine** [comment]
Thanks!
