### ISSUE TITLE
urec.c:129:8: warning: ordered compariso n of pointer with integer zero [-Wextra]

### ISSUE THREAD

**Issue by dcb314** [rpodgorny/uptimed#8]
Source code is

```
f=fopen("/proc/uptime", "r");
if (f > 0) {
```

Maybe better code

```
f=fopen("/proc/uptime", "r");
if (f != NULL) {
```

**Comment by rpodgorny** [comment]
thanks! ...please try https://github.com/rpodgorny/uptimed/tree/fopen to see if it's better now for you...

**Comment by rpodgorny** [comment]
the code has changed meanwhile - this should no longer be an issue.
